//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.24 at 10:26:12 AM BRT 
//


package br.com.ttrans.samapp.ws.bo.alarm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 * <p>Java class for AlarmDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AlarmDetail">
 *   &lt;complexContent>
 *     &lt;extension base="{http://samapp.ttrans.com.br/services/AlarmServices/xsd}AlarmBase">
 *       &lt;sequence>
 *         &lt;element name="alarmTypeId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stateId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="severity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="objectId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="areaId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apparitionDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="sopId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="textMessageId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="textMessageParams" type="{http://samapp.ttrans.com.br/services/AlarmServices/xsd}MessageParams" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="priorityId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;any processContents='lax' namespace='http://samapp.ttrans.com.br/services/AlarmServices/xsd' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AlarmDetail", propOrder = {
    "alarmTypeId",
    "stateId",
    "severity",
    "objectId",
    "areaId",
    "apparitionDate",
    "sopId",
    "textMessageId",
    "textMessageParams",
    "priorityId",
    "any"
})
@XmlSeeAlso({
    AlarmAdd.class
})
public class AlarmDetail
    extends AlarmBase
{

    @XmlElement(required = true)
    protected String alarmTypeId;
    protected int stateId;
    protected int severity;
    @XmlElement(required = true)
    protected String objectId;
    @XmlElement(required = true)
    protected String areaId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar apparitionDate;
    protected String sopId;
    @XmlElement(required = true)
    protected String textMessageId;
    protected List<MessageParams> textMessageParams;
    protected int priorityId;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the alarmTypeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlarmTypeId() {
        return alarmTypeId;
    }

    /**
     * Sets the value of the alarmTypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlarmTypeId(String value) {
        this.alarmTypeId = value;
    }

    /**
     * Gets the value of the stateId property.
     * 
     */
    public int getStateId() {
        return stateId;
    }

    /**
     * Sets the value of the stateId property.
     * 
     */
    public void setStateId(int value) {
        this.stateId = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     */
    public int getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     */
    public void setSeverity(int value) {
        this.severity = value;
    }

    /**
     * Gets the value of the objectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectId() {
        return objectId;
    }

    /**
     * Sets the value of the objectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectId(String value) {
        this.objectId = value;
    }

    /**
     * Gets the value of the areaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * Sets the value of the areaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaId(String value) {
        this.areaId = value;
    }

    /**
     * Gets the value of the apparitionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getApparitionDate() {
        return apparitionDate;
    }

    /**
     * Sets the value of the apparitionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setApparitionDate(XMLGregorianCalendar value) {
        this.apparitionDate = value;
    }

    /**
     * Gets the value of the sopId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSopId() {
        return sopId;
    }

    /**
     * Sets the value of the sopId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSopId(String value) {
        this.sopId = value;
    }

    /**
     * Gets the value of the textMessageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextMessageId() {
        return textMessageId;
    }

    /**
     * Sets the value of the textMessageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextMessageId(String value) {
        this.textMessageId = value;
    }

    /**
     * Gets the value of the textMessageParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textMessageParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextMessageParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageParams }
     * 
     * 
     */
    public List<MessageParams> getTextMessageParams() {
        if (textMessageParams == null) {
            textMessageParams = new ArrayList<MessageParams>();
        }
        return this.textMessageParams;
    }

    /**
     * Gets the value of the priorityId property.
     * 
     */
    public int getPriorityId() {
        return priorityId;
    }

    /**
     * Sets the value of the priorityId property.
     * 
     */
    public void setPriorityId(int value) {
        this.priorityId = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     {@link Element }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
