//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.22 at 02:00:45 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://samapp.ttrans.com.br/services/SystemServices/xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.ttrans.samapp.ws.bo.system;
